### ISSUE TITLE
Upload .json files

### ISSUE THREAD

**Issue by nalo26** [tbarnes94/fortnite-weapons-bot#1]
Can you please upload .json files of the weapons ? The code doesn't work for me and I don't know how to fix it. In fact, I just need the weapon json files, I don't need the rest :)
Ty :D

**Comment by tbarnes94** [comment]
Sorry I realize my repo isn't very helpful.  I've just sort of used it for my own server.

Here's the OAuth2 link to add to your server: https://discordapp.com/api/oauth2/authorize?client_id=421261707906908162&permissions=18432&scope=bot

Try this before I do that.  I'm happy to send you the JSONs after.

1. Run cmd as administrator.
2. **npm i -g typescipt** <- you need the Typescript Compiler to transpile .ts files into .js
3. **cd** into the root folder of the cloned repo
4. **npm i** <- install the npm dependencies
5. **tsc** <- transpiles all the .ts files in the directory into .js files
6. **node ./src/web-crawlers/all/weapon-crawler-all.js** <-- Scrapes HTML from https://db.fortnitetracker.com/weapons and converts into one JSON
7. **node ./src/web-crawlers/one/weapon-crawler-one.js** <-- Scrapes HTML from https://db.fortnitetracker.com/weapons/* and converts into * number of JSONs

At this point you should have all the JSONs in the ./src/databases folder based on the up to date db.fortnitetracker.com.

**Comment by tbarnes94** [comment]
[Here are the JSONs you requested.](https://github.com/tbarnes94/fortnite-weapons-bot/files/2229362/weapons.zip)
